name: fast_image
description: A new flutter plugin project.
version: 1.0.0
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  fast_image_platform_interface:
    path: ../fast_image_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.darttools.fast_image
        pluginClass: FastImagePlugin
